version: "3.9"

#If you typed wrong password in adminer,
#"docker compose down" and then "docker compose up"
#! docker compose exec -it db psql -U root -d gallery

services:
  #Name of the service
  db:
    image: postgres:15-alpine
    restart: always
    #Env variables
    #these vars should be at start up to create user
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gallery
    ports:
    #port 3030 on pc maps to 5432 on docker vm
    #so in Conn string host=localhost port=3030... will connect to docker postgres
      - "3030:5432"