version: "3.9"

#If you typed wrong password in adminer,
#"docker compose down" and then "docker compose up"

#! docker compose exec -it db psql -U root -d gallery
#string value in postgres - first_name text;
services:
  #database
  #Name of the service
  db:
    image: postgres
    restart: always
    #Env variables
    #these vars should be at start up to create user
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gallery
    ports:
    #port 3030 on pc maps to 5432 on docker vm
    #so in Conn string host=localhost port=3030... will connect to docker postgres
      - "5432:5432"

  #Adminer provides web UI to connect to db
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - "3333:8080"